name: CI
on: 
  #push:
  #  branches: [ master ]
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
